### ISSUE TITLE
[BUG] Redeploying with another env configuration leads to broken state on every page opening

### ISSUE THREAD

**Issue by MaxLevs** [jocxfin/pwgen#97]
**Describe the bug**
If app is hosted in docker compose, you can change envs to change configuration.
But when it happens app still loads page as if config wasn't changed. More over it leads to infinity `load` of generated passwords.

**To Reproduce**
1.  Host application with following compose.yaml
```yaml
services:
  pwgen:
    image: jocxfin/pwgen:latest
    environment:
      GENERATE_PP: true
```
2. Open hosted app in your browser update it several times and generate several passwords with button
3. Change configuration in compose.yaml with following
```yaml
services:
  pwgen:
    image: jocxfin/pwgen:latest
    environment:
      PW_LENGTH: 20
      MULTI_GEN: true
      PW_INCLUDE_UPPERCASE: true
      PW_INCLUDE_DIGITS: true
      PW_INCLUDE_SPECIAL: true
      PW_EXCLUDE_HOMOGLYPHS: true
      GENERATE_PP: false
```
4. Reload page

**Actual behaviour**
Page load with old config. Generation request finished but result cannot be printed. Infinity loader.

**Expected behaviour**
Page was regenerated to follow new configuration. First automatic generation request result was displayed.

**Screenshots**

firt deploy
![first deploy](https://github.com/user-attachments/assets/698ef8d7-1e5f-4292-a8d0-02dcf3e1f7b1)

second deploy
![second deploy](https://github.com/user-attachments/assets/737f106d-0f52-4d5d-a08d-3748ac29359f)

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome 133.0.6943.99
 - Version: 1.92.5 (if you asked about pwgen version)

**Additional context**

**Comment by MaxLevs** [comment]
Actually it's problem with `service-worker.js`.
I believe that root page musn't be cached. But a cache code appears strange to me. I just don't get it why we add some pages on installing and then just cache all pages from GET. 

I could only come up with deleting the `/` from "pre-cache" on installing and workaround to filter it from further caching in "fetch".
But I don't think it's good enouth to send this fixes as some sort of real solution.

**Comment by jocxfin** [comment]
@MaxLevs i actually tried to reproduce this after i had made the changes already but im not able to reproduce this with

```yaml
services:
  pwgen:
    image: jocxfin/pwgen:latest
    environment:
      PW_LENGTH: 20
      MULTI_GEN: true
      PW_INCLUDE_UPPERCASE: true
      PW_INCLUDE_DIGITS: true
      PW_INCLUDE_SPECIAL: true
      PW_EXCLUDE_HOMOGLYPHS: true
      GENERATE_PP: false
    ports:
      - "5069:5069"
```

![Image](https://github.com/user-attachments/assets/eff920ea-c9d2-45a4-8d5e-a12a0019d9df)
